name: Check and push a package
on:
  workflow_call:
    inputs: 
      PROJECT:
        description: Project Name
        required: true
        type: string
      SONAR_TOKEN:
        description: Sonar Token
        required: true
        type: string
      SONAR_KEY:
        description: Sonar Key
        required: true
        type: string
jobs: 
  Sonar:
    uses: LoafThePenguin/actions/.github/workflows/Sonar.yml@main
    with:
      PROJECT: ${{ inputs.PROJECT }}
      TOKEN: ${{ inputs.SONAR_TOKEN }}
      KEY: ${{ inputs.SONAR_KEY }}
  PushPackage:
    needs: [Sonar]
    uses: LoafThePenguin/actions/.github/workflows/PushPackage.yml@main
    with:
      PROJECT: ${{ inputs.PROJECT }}
  Tag: 
    needs: [PushPackage]
    uses: LoafThePenguin/actions/.github/workflows/CreateReleaseTag.yml@main
