name: Check and push a package
on:
  workflow_call:
jobs: 
  Sonar:
    uses: LoafThePenguin/actions/.github/workflows/Sonar.yml@main
  PushPackage:
    needs: [Sonar]
    uses: LoafThePenguin/actions/.github/workflows/PushPackage.yml@main
  Tag: 
    needs: [PushPackage]
    uses: LoafThePenguin/actions/.github/workflows/CreateReleaseTag.yml@main
