name: Check and push a package
on:
      workflow_call:
        inputs:
            project:
                description: Project will check
                required: true
                type: string
            key:
                description: Sonar Key
                required: true
                type: string
        secrets:
            SONAR_TOKEN: 
                required: true
jobs: 
    Package:
        name: Check and push a package
        runs-on: windows-latest
        steps:
            - name: Sonar Check
              uses: /Sonar.yml
              with:
                  prioject: ${{ inputs.project }}
                  key: ${{ inputs.project }}
              secrets:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            - name: Push Package
              uses: /PushPackage.yml
              with:
                  project: ${{ inputs.project }}
            - name: Create Release Tag
              uses: /CreateReleaseTag.yml
