name: Create Tag
on:
  workflow_call:
jobs: 
  Version:
    name: Version
    uses: LoafThePenguin/actions/.github/workflows/Version.yml@main
  Create-Tag:
    name: Create Tag
    needs: [Version]
    runs-on: windows-latest
    steps:
      - run: echo "previous_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo '')" >> $GITHUB_ENV
      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@main
        if: env.previous_tag
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release: true
          version: ${{ needs.Version.outputs.version }}
