name: Push Package
on:
  workflow_call:
jobs: 
  Package:
    name: Package
    runs-on: windows-latest
    steps:
      - name: Pack Package
        run: dotnet pack src/${{ secrets.PROJECT }} -c Release
      - name: Push Package
        run: dotnet nuget push "**/${{ secrets.PROJECT }}/artifacts/Release/nupkg/*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/LoafThePenguin/index.json
