name: Push Package
on:
  workflow_call:
    inputs: 
      PROJECT:
        description: Project Name
        required: true
        type: string
jobs: 
  Package:
    name: Package
    runs-on: windows-latest
    steps:
      - name: Pack Package
        run: dotnet pack src/${{ inputs.PROJECT }} -c Release
      - name: Push Package
        run: dotnet nuget push "**/${{ inputs.PROJECT }}/artifacts/Release/nupkg/*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/LoafThePenguin/index.json
